# Generated by Django 5.2.12 on 2026-04-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mentorfollow'),
        ('account', '0005_mentorverificationrequest'),
    ]

    operations = [
    ]
