# Generated by Django 5.2.12 on 2026-04-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataset", "0006_merge_0002_mentor_owner_0005_paper_arxiv_url"),
        ("account", "0006_merge_20260426_1300"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPushPaperBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cycle", models.CharField(choices=[("current", "当前周期"), ("next", "下一个周期"), ("archived", "已归档周期")], max_length=20, verbose_name="周期类型")),
                ("day_key", models.CharField(max_length=20, verbose_name="星期键")),
                ("archive_batch", models.CharField(blank=True, default="", max_length=64, verbose_name="归档批次")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paper", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="weekly_push_buckets", to="dataset.paper")),
            ],
            options={
                "ordering": ["cycle", "day_key", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklypushpaperbucket",
            constraint=models.UniqueConstraint(fields=("cycle", "day_key", "paper"), name="unique_weekly_push_cycle_day_paper"),
        ),
    ]
