# Generated by Django 5.2.12 on 2026-04-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_weeklypushpaperbucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("weekly", "周报")], max_length=20, verbose_name="推送类型")),
                ("period_key", models.CharField(max_length=64, verbose_name="周期键")),
                ("period_start", models.DateTimeField(verbose_name="周期开始时间")),
                ("period_end", models.DateTimeField(verbose_name="周期结束时间")),
                ("status", models.CharField(choices=[("pending", "待发送"), ("sent", "发送成功"), ("failed", "发送失败")], default="pending", max_length=20)),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="发送时间")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, default="", verbose_name="失败信息")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="push_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="pushrecord",
            constraint=models.UniqueConstraint(fields=("user", "type", "period_key"), name="unique_push_record_user_type_period"),
        ),
    ]
