# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_weeklypushpaperbucket_period_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="personal_intro",
            field=models.TextField(blank=True, default="", verbose_name="个人简介"),
        ),
    ]
