# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_userprofile_personal_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.TextField(blank=True, default="", verbose_name="头像地址"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="个性签名"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_personal_intro",
            field=models.BooleanField(default=True, verbose_name="展示个人简介"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_research_experience",
            field=models.BooleanField(default=True, verbose_name="展示科研经历"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_honors",
            field=models.BooleanField(default=True, verbose_name="展示所获荣誉"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_project_experience",
            field=models.BooleanField(default=True, verbose_name="展示项目经历"),
        ),
    ]
