# Generated by Claude on 2026-05-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_merge_0013_emailverificationcode_0013_subjectfollow"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWeeklyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField(verbose_name="周开始日期")),
                ("week_end", models.DateField(verbose_name="周结束日期")),
                ("title", models.CharField(max_length=255, verbose_name="周报标题")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="前端展示完整结构")),
                ("digest", models.JSONField(blank=True, default=dict, verbose_name="邮件构造用 digest")),
                ("has_updates", models.BooleanField(default=False, verbose_name="是否有命中论文")),
                ("total_paper_count", models.IntegerField(default=0, verbose_name="命中论文总数")),
                (
                    "generated_by_kind",
                    models.CharField(
                        choices=[("user", "用户手动生成"), ("scheduled", "定时任务生成")],
                        default="user",
                        max_length=20,
                        verbose_name="生成方式",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True, verbose_name="最近生成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="首次生成时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户专属周报",
                "verbose_name_plural": "用户专属周报",
                "ordering": ["-week_start", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="userweeklyreport",
            constraint=models.UniqueConstraint(
                fields=("user", "week_start"),
                name="unique_user_weekly_report_user_week",
            ),
        ),
    ]
