# Generated by security hardening on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_emailverificationcode_attempt_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_token_version",
            field=models.PositiveIntegerField(default=0, verbose_name="JWT 吊销版本"),
        ),
    ]
