# Generated by Django 5.1.6 on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_userprofile_mentorfollow"),
        ("dataset", "0002_mentor_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("mentor", "导师"),
                    ("admin", "系统管理员"),
                    ("banned", "已封禁"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mentor_profile",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"owner__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bound_user",
                to="dataset.mentor",
                verbose_name="绑定公共导师",
            ),
        ),
    ]
