# Generated by Django 5.2.12 on 2026-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_pushrecord"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="weeklypushpaperbucket",
            name="unique_weekly_push_cycle_day_paper",
        ),
        migrations.AddField(
            model_name="weeklypushpaperbucket",
            name="period_key",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="周期键"),
        ),
        migrations.AlterModelOptions(
            name="weeklypushpaperbucket",
            options={"ordering": ["cycle", "period_key", "day_key", "id"]},
        ),
        migrations.AddConstraint(
            model_name="weeklypushpaperbucket",
            constraint=models.UniqueConstraint(
                fields=("cycle", "period_key", "day_key", "paper"),
                name="unique_weekly_push_cycle_period_day_paper",
            ),
        ),
    ]
