# Generated by Codex on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_emailverificationcode"),
        ("account", "0013_subjectfollow"),
    ]

    operations = []
