# Generated by Claude on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_userweeklyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0, verbose_name="校验失败次数"),
        ),
    ]
