"""Django settings for MFBackend project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/

中文说明：
- 本文件包含项目运行所需的核心配置：数据库、已安装应用、
    中间件、静态/媒体路径、邮件/外部服务配置及安全相关设置。
- 生产环境中请通过环境变量或受信任的 secrets 管理凭证，避免将
    明文密钥（如 `SECRET_KEY`、外部 API 密钥）提交到代码仓库。
- 请在部署前根据生产要求调整 `DEBUG`、`ALLOWED_HOSTS`、数据库
    与邮件等配置，确保安全与性能。
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load <BASE_DIR>/.env so secrets like the 163 SMTP auth code don't need to be
# exported manually on every deploy. The .env file stays gitignored.
try:
    from dotenv import load_dotenv as _load_dotenv
    _load_dotenv(BASE_DIR / ".env")
except ModuleNotFoundError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from the DJANGO_SECRET_KEY environment variable (written into .env by CI,
# same mechanism as the 163 SMTP / superuser credentials). The insecure fallback
# only exists so local development without a .env keeps working; deployment MUST
# provide DJANGO_SECRET_KEY (enforced in .gitlab-ci.yml).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-xvv16d@^4vu6-_^8w73_wt+xqf-wfppqevn)_zgye!#7l^6=p$',
)

# SECURITY WARNING: don't run with debug turned on in production!
# TODO Start: [Student] Disable debug mode in production
DEBUG = False
# TODO End: [Student] Disable debug mode in production


ALLOWED_HOSTS = [
    '*'  # Insecure
]


# Application definition

INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'search',
    'dataset',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MFBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MFBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }  # Change to MySQL or other databases for your FINAL project
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# 163 SMTP integration. When EMAIL_HOST_USER and EMAIL_HOST_PASSWORD are both set
# via environment variables, the SMTP backend is used; otherwise we fall back to
# the console backend so local development never tries to send real mail.
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.163.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'true').lower() in ('1', 'true', 'yes')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'false').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))

_smtp_configured = bool(EMAIL_HOST_USER) and bool(EMAIL_HOST_PASSWORD)
_default_email_backend = (
    'django.core.mail.backends.smtp.EmailBackend'
    if _smtp_configured
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', _default_email_backend)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    (f'MentorFinder <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'MentorFinder <no-reply@mentorfinder.local>'),
)

EMAIL_VERIFICATION_CODE_TTL_SECONDS = int(os.environ.get('EMAIL_VERIFICATION_CODE_TTL', '600'))
EMAIL_VERIFICATION_CODE_RESEND_COOLDOWN = int(os.environ.get('EMAIL_VERIFICATION_CODE_COOLDOWN', '60'))

# AI weekly push (OpenAI-compatible API provided by THU CS lab)
# Keep API key empty in repo, fill through environment variable in deployment.
# THUCS_API_BASE_URL = os.environ.get('THUCS_API_BASE_URL', 'https://api-ai.thucs.cn')
# THUCS_API_BASE_URL = os.environ.get('THUCS_API_BASE_URL', "")
# THUCS_API_KEY = os.environ.get('THUCS_API_KEY', '')
THUCS_API_BASE_URL = os.environ.get('THUCS_API_BASE_URL', "")
THUCS_API_KEY = os.environ.get('THUCS_API_KEY', '')
# THUCS_MODEL_NAME = os.environ.get('THUCS_MODEL_NAME', 'qwen-plus')
THUCS_MODEL_NAME = os.environ.get('THUCS_MODEL_NAME', 'deepseek-v4-flash')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'account.User'
